version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    depends_on:
      - nodeapp

  nodeapp:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # environment:
    #   - PORT=3000
    #   - JWT_SECRET=<JWT_SECRET>
    #   - CLOUDINARY_NAME=<CLOUDINARY_NAME>
    #   - CLOUDINARY_API_KEY=<CLOUDINARY_API_KEY>
    #   - CLOUDINARY_API_SECRET=<CLOUDINARY_API_SECRET>
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rohit
      - MONGO_INITDB_ROOT_PASSWORD=rohit
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
